2022-03-03 06:43:25,278 ERROR 43771 nodejs.ClusterClientNoResponseError: client no response in 43262177ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 43771
hostname: talkdeMacBook-Pro.local

2022-03-03 10:28:29,590 ERROR 43771 nodejs.ClusterClientNoResponseError: client no response in 13504309ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 43771
hostname: talkdeMacBook-Pro.local

2022-03-03 11:05:42,243 ERROR 43775 [-//-/947ms POST /graphql] getTokenByRefreshToken-error
2022-03-03 11:05:46,901 ERROR 43775 [-//-/1162ms POST /graphql] getTokenByRefreshToken-error
2022-03-03 11:06:25,402 ERROR 43775 [-//-/1076ms POST /graphql] getTokenByRefreshToken-error
2022-03-03 11:06:43,321 ERROR 43775 [-//-/1113ms POST /graphql] getTokenByRefreshToken-error
2022-03-03 11:08:47,847 ERROR 43775 [-//-/969ms POST /graphql] getTokenByRefreshToken-error
2022-03-03 11:08:51,404 ERROR 43775 [-//-/1089ms POST /graphql] getTokenByRefreshToken-error
2022-03-03 11:22:43,552 ERROR 43775 [-//-/1142ms POST /graphql] getTokenByRefreshToken-error
2022-03-03 11:22:53,223 ERROR 43775 [-//-/974ms POST /graphql] getTokenByRefreshToken-error
2022-03-03 11:22:59,345 ERROR 43775 [-//-/935ms POST /graphql] getTokenByRefreshToken-error
2022-03-03 11:26:13,142 ERROR 43775 [-//-/1113ms POST /graphql] getTokenByRefreshToken-error
2022-03-03 11:26:18,109 ERROR 43775 [-//-/1124ms POST /graphql] getTokenByRefreshToken-error
2022-03-03 11:26:49,661 ERROR 43775 [-//-/1166ms POST /graphql] getTokenByRefreshToken-error
2022-03-03 11:27:57,105 ERROR 43775 [-//-/966ms POST /graphql] getTokenByRefreshToken-error
2022-03-03 11:28:31,375 ERROR 43775 [-//-/942ms POST /graphql] getTokenByRefreshToken-error
2022-03-03 12:36:14,348 ERROR 43771 nodejs.ClusterClientNoResponseError: client no response in 943745ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 43771
hostname: talkdeMacBook-Pro.local

2022-03-03 14:02:56,611 ERROR 43771 nodejs.ClusterClientNoResponseError: client no response in 5202245ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 43771
hostname: talkdeMacBook-Pro.local

2022-03-03 14:24:21,821 ERROR 43775 [-//-/1130ms POST /graphql] getTokenByRefreshToken-error
2022-03-03 14:24:32,213 ERROR 43775 [-//-/1036ms POST /graphql] getTokenByRefreshToken-error
2022-03-18 09:26:33,911 ERROR 10811 [egg-redis] client error: Error: connect ECONNREFUSED 127.0.0.1:6379
2022-03-18 09:26:33,912 ERROR 10811 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 10811
hostname: talkdeMacBook-Pro.local

2022-03-18 09:26:33,913 ERROR 10811 [egg-redis] client error: Error: connect ECONNREFUSED 127.0.0.1:6379
2022-03-18 09:26:33,913 ERROR 10811 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 10811
hostname: talkdeMacBook-Pro.local

2022-03-18 09:26:33,914 ERROR 10811 [egg-redis] client error: Error: connect ECONNREFUSED 127.0.0.1:6379
2022-03-18 09:26:33,914 ERROR 10811 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 10811
hostname: talkdeMacBook-Pro.local

2022-03-18 09:26:33,916 ERROR 10811 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 10811
hostname: talkdeMacBook-Pro.local

2022-03-18 09:26:33,916 ERROR 10811 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 10811
hostname: talkdeMacBook-Pro.local

2022-03-18 09:26:33,917 ERROR 10811 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 10811
hostname: talkdeMacBook-Pro.local

2022-03-18 09:29:12,274 ERROR 10876 [-//-/674ms POST /graphql] getTokenByRefreshToken-error
2022-03-18 09:29:17,017 ERROR 10876 [-//-/493ms POST /graphql] getTokenByRefreshToken-error
2022-03-18 17:33:45,321 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 28818754ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-18 19:33:21,775 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 7176432ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-19 08:20:13,616 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 43271519ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-19 17:44:01,677 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 33828019ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-19 17:44:42,610 ERROR 10876 [-/127.0.0.1/-/50ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest catch request error {"cause":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443},"isOperational":true,"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443}
2022-03-19 17:44:42,611 ERROR 10876 [-/127.0.0.1/-/54ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"message":"getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443"}} {}
2022-03-19 17:44:42,615 ERROR 10876 [-/127.0.0.1/-/58ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443
2022-03-20 01:55:18,535 ERROR 10876 [-/127.0.0.1/-/108ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest catch request error {"cause":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443},"isOperational":true,"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443}
2022-03-20 01:55:18,551 ERROR 10876 [-/127.0.0.1/-/121ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"message":"getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443"}} {}
2022-03-20 01:55:18,556 ERROR 10876 [-/127.0.0.1/-/129ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443
2022-03-20 01:55:18,426 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 28616443ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-20 13:56:53,188 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 43274487ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-21 09:21:40,648 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 69887422ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-21 10:06:03,327 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 2462082ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-21 10:12:55,665 ERROR 10876 [-//-/567ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 10:12:56,232 ERROR 10876 [-//-/476ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 10:12:58,446 ERROR 10876 [-//-/470ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 10:18:48,248 ERROR 10876 [-//-/475ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 10:18:54,493 ERROR 10876 [-//-/495ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 10:29:34,453 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 90680ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-21 10:29:35,813 ERROR 10876 [-/127.0.0.1/-/1253ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest catch request error {"cause":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443},"isOperational":true,"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443}
2022-03-21 10:29:35,815 ERROR 10876 [-/127.0.0.1/-/1254ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"message":"getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443"}} {}
2022-03-21 10:29:35,816 ERROR 10876 [-/127.0.0.1/-/1257ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443
2022-03-21 11:40:32,073 ERROR 10876 [-//-/485ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 11:40:59,657 ERROR 10876 [-//-/482ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 11:41:40,525 ERROR 10876 [-//-/464ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 11:41:47,263 ERROR 10876 [-//-/462ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 11:42:22,519 ERROR 10876 [-//-/485ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 11:42:54,404 ERROR 10876 [-//-/498ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 11:44:01,499 ERROR 10876 [-//-/397ms POST /graphql] GeneralRequest error userSignin {"error":{"code":2014,"message":"Incorrect username or password.  You have 4 more tries left.","reason":"login_failed"}} {"email":"deng11092021@163.com","password":"Qwer1234!!11","id_type":"3","id_value":"fb224e86690861c172548c73eb8f9ecb64478915","token":"ae14e00fc928a06c423a00c8055b4d75|jordan","session_id":"e076587d826f1ee2c82855b4e7824d4a"}
2022-03-21 11:44:48,977 ERROR 10876 [-//-/474ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 11:45:34,438 ERROR 10876 [-//-/473ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 11:49:12,508 ERROR 10876 [-//-/1057ms POST /graphql] GeneralRequest error userSigninWithAcl {"error":{"code":2001,"message":"login required!","reason":"login_required"}} {"session_id":"e076587d826f1ee2c82855b4e7824d4a"}
2022-03-21 11:49:13,565 ERROR 10876 [-//-/798ms POST /graphql] GeneralRequest error userSigninWithAcl {"error":{"code":2001,"message":"login required!","reason":"login_required"}} {"session_id":"e076587d826f1ee2c82855b4e7824d4a"}
2022-03-21 11:49:14,117 ERROR 10876 [-//-/699ms POST /graphql] GeneralRequest error userSigninWithAcl {"error":{"code":2001,"message":"login required!","reason":"login_required"}} {"session_id":"e076587d826f1ee2c82855b4e7824d4a"}
2022-03-21 11:49:14,282 ERROR 10876 [-//-/703ms POST /graphql] GeneralRequest error userSigninWithAcl {"error":{"code":2001,"message":"login required!","reason":"login_required"}} {"session_id":"e076587d826f1ee2c82855b4e7824d4a"}
2022-03-21 11:49:14,440 ERROR 10876 [-//-/712ms POST /graphql] GeneralRequest error userSigninWithAcl {"error":{"code":2001,"message":"login required!","reason":"login_required"}} {"session_id":"e076587d826f1ee2c82855b4e7824d4a"}
2022-03-21 11:49:22,588 ERROR 10876 [-//-/499ms POST /pusher/auth] getTokenByRefreshToken-error
2022-03-21 11:49:22,589 ERROR 10876 [-//-/500ms POST /pusher/auth] GeneralRequest catch request error {}
2022-03-21 11:49:22,589 ERROR 10876 [-//-/500ms POST /pusher/auth] GeneralRequest error pusherAuth {"error":{"message":"getTokenByRefreshToken-error"}} {"socket_id":"1.639201","channel_name":"private-PEAIV4WTBQGTIO"}
2022-03-21 11:49:22,589 ERROR 10876 [-//-/500ms POST /pusher/auth] pusherAuth error :  { Error: getTokenByRefreshToken-error
    at GenegralRequestService.request (/Users/talk/Desktop/document/rio/exchange/portal/app/service/generalRequest.js:78:19)
    at process._tickCallback (internal/process/next_tick.js:68:7) message: 'getTokenByRefreshToken-error' }
2022-03-21 11:49:23,641 ERROR 10876 [-//-/495ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 11:49:24,147 ERROR 10876 [-//-/491ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 11:49:24,724 ERROR 10876 [-//-/562ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 11:49:25,291 ERROR 10876 [-//-/556ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 11:49:27,523 ERROR 10876 [-//-/655ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 11:49:30,414 ERROR 10876 [-//-/542ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 11:50:10,690 ERROR 10876 [-//-/610ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 11:50:49,950 ERROR 10876 [-//-/469ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 11:50:50,456 ERROR 10876 [-//-/481ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 11:50:54,664 ERROR 10876 [-//-/488ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 11:51:11,029 ERROR 10876 [-//-/509ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 11:51:11,856 ERROR 10876 [-//-/784ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 11:51:15,050 ERROR 10876 [-//-/1504ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 11:51:58,872 ERROR 10876 [-//-/705ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 11:51:59,493 ERROR 10876 [-//-/598ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 11:52:01,423 ERROR 10876 [-//-/735ms POST /graphql] getTokenByRefreshToken-error
2022-03-21 12:37:06,545 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 109456ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-22 00:42:39,594 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 43272993ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-22 11:33:41,827 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 39062206ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-22 12:16:04,102 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 301854ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-22 13:34:28,180 ERROR 10876 [-/127.0.0.1/-/4684930ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"code":20051,"message":"","reason":"incorrect_signature_expired"}} {}
2022-03-22 13:34:28,182 ERROR 10876 [-/127.0.0.1/-/4684932ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: incorrect_signature_expired
2022-03-22 13:51:47,139 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 5722995ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-23 01:54:40,592 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 43273401ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-23 14:51:38,925 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 46618307ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-23 15:21:40,880 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 681812ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-23 18:17:55,918 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 8674779ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-23 18:43:15,948 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 215992ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-23 19:23:28,540 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 1892527ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-23 20:32:13,147 ERROR 10876 [-/127.0.0.1/-/3605833ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"code":20051,"message":"","reason":"incorrect_signature_expired"}} {}
2022-03-23 20:32:13,149 ERROR 10876 [-/127.0.0.1/-/3605835ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: incorrect_signature_expired
2022-03-24 05:38:13,304 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 36364668ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-24 07:33:20,499 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 6907158ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-24 09:12:24,485 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 5943966ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-24 09:47:14,322 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 649707ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-24 10:43:08,439 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 1213791ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-24 16:13:35,966 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 18687272ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-24 19:19:21,522 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 10804492ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-03-25 10:29:56,835 ERROR 10875 nodejs.ClusterClientNoResponseError: client no response in 54635112ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10875
hostname: talkdeMacBook-Pro.local

2022-04-05 11:26:21,882 ERROR 18597 [egg-redis] client error: Error: connect ECONNREFUSED 127.0.0.1:6379
2022-04-05 11:26:21,883 ERROR 18597 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 18597
hostname: talkdeMacBook-Pro.local

2022-04-05 11:26:21,884 ERROR 18597 [egg-redis] client error: Error: connect ECONNREFUSED 127.0.0.1:6379
2022-04-05 11:26:21,884 ERROR 18597 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 18597
hostname: talkdeMacBook-Pro.local

2022-04-05 11:26:21,885 ERROR 18597 [egg-redis] client error: Error: connect ECONNREFUSED 127.0.0.1:6379
2022-04-05 11:26:21,885 ERROR 18597 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 18597
hostname: talkdeMacBook-Pro.local

2022-04-05 11:26:21,887 ERROR 18597 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 18597
hostname: talkdeMacBook-Pro.local

2022-04-05 11:26:21,888 ERROR 18597 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 18597
hostname: talkdeMacBook-Pro.local

2022-04-05 11:26:21,888 ERROR 18597 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 18597
hostname: talkdeMacBook-Pro.local

2022-04-05 11:33:59,109 ERROR 920 [-//-/3302ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 11:35:47,336 ERROR 920 [-/127.0.0.1/-/30017ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest catch request error {"cause":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443},"isOperational":true,"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443}
2022-04-05 11:35:47,337 ERROR 920 [-/127.0.0.1/-/30018ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"message":"getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443"}} {}
2022-04-05 11:35:47,337 ERROR 920 [-/127.0.0.1/-/30018ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443
2022-04-05 11:36:59,992 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 62248ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-05 12:17:42,501 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 2354458ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-05 15:28:32,116 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 10989481ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-05 15:36:45,576 ERROR 920 [-//-/691ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 15:36:48,133 ERROR 920 [-//-/490ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 15:38:48,889 ERROR 920 [-//-/580ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 15:39:01,712 ERROR 920 [-//-/924ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 15:39:04,456 ERROR 920 [-//-/685ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 15:39:09,073 ERROR 920 [-//-/634ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 15:39:22,379 ERROR 920 [-//-/554ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 16:45:54,795 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 301918ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-05 16:53:39,038 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 464240ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-05 16:56:33,993 ERROR 920 [-//-/614ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 16:59:12,155 ERROR 920 [-//-/581ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 17:14:40,039 ERROR 920 [-//-/704ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 17:15:46,429 ERROR 920 [-//-/510ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 17:26:04,554 ERROR 920 [-//-/660ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:13:51,524 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 9492118ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-05 20:13:59,405 ERROR 920 [-//-/1815ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:14:04,185 ERROR 920 [-//-/629ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:17:01,688 ERROR 920 [-//-/1406ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:17:39,908 ERROR 920 [-//-/2464ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:19:42,469 ERROR 920 [-//-/7219ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:19:58,948 ERROR 920 [-//-/630ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:20:23,245 ERROR 920 [-//-/529ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:20:44,707 ERROR 920 [-//-/507ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:20:50,723 ERROR 920 [-//-/966ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:21:10,546 ERROR 920 [-//-/678ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:21:11,308 ERROR 920 [-//-/738ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:21:16,288 ERROR 920 [-//-/1753ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:21:19,144 ERROR 920 [-//-/1017ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:21:22,849 ERROR 920 [-//-/513ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:22:16,214 ERROR 920 [-//-/743ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:22:17,428 ERROR 920 [-//-/1769ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:22:22,194 ERROR 920 [-//-/738ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:22:32,094 ERROR 920 [-//-/519ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:22:38,094 ERROR 920 [-//-/613ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:22:43,773 ERROR 920 [-//-/624ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:23:01,788 ERROR 920 [-//-/710ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:23:02,082 ERROR 920 [-//-/1057ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:23:05,171 ERROR 920 [-//-/705ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:23:06,402 ERROR 920 [-//-/559ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:23:06,436 ERROR 920 [-//-/613ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:23:07,165 ERROR 920 [-//-/677ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:23:10,901 ERROR 920 [-//-/737ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:23:18,742 ERROR 920 [-//-/639ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:23:54,916 ERROR 920 [-//-/527ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:23:55,836 ERROR 920 [-//-/713ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:23:59,217 ERROR 920 [-//-/752ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:24:11,178 ERROR 920 [-//-/651ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:24:15,884 ERROR 920 [-//-/825ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:25:07,211 ERROR 920 [-//-/997ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:25:17,914 ERROR 920 [-//-/645ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:25:42,762 ERROR 920 [-//-/647ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:31:52,908 ERROR 920 [-//-/761ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:40:00,758 ERROR 920 [-//-/626ms POST /graphql] getTokenByRefreshToken-error
2022-04-05 20:54:00,312 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 408407ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-05 22:05:57,593 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 2185923ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-06 10:28:06,042 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 42707980ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-06 10:28:12,286 ERROR 920 [-/127.0.0.1/-/5398ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest catch request error {"cause":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443},"isOperational":true,"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443}
2022-04-06 10:28:12,286 ERROR 920 [-/127.0.0.1/-/5399ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"message":"getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443"}} {}
2022-04-06 10:28:12,286 ERROR 920 [-/127.0.0.1/-/5399ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443
2022-04-06 10:32:35,881 ERROR 920 [-//-/603ms POST /graphql] getTokenByRefreshToken-error
2022-04-06 10:32:55,529 ERROR 920 [-//-/1293ms POST /graphql] getTokenByRefreshToken-error
2022-04-06 11:09:21,911 ERROR 920 [-/127.0.0.1/-/1454971ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest catch request error {"cause":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443},"isOperational":true,"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443}
2022-04-06 11:09:21,912 ERROR 920 [-/127.0.0.1/-/1454972ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"message":"getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443"}} {}
2022-04-06 11:09:21,912 ERROR 920 [-/127.0.0.1/-/1454972ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443
2022-04-06 11:09:38,445 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 1472256ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-06 15:36:55,492 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 15837014ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-06 16:06:55,611 ERROR 920 [-/127.0.0.1/-/9ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest catch request error {"cause":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443},"isOperational":true,"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443}
2022-04-06 16:06:55,611 ERROR 920 [-/127.0.0.1/-/9ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"message":"getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443"}} {}
2022-04-06 16:06:55,611 ERROR 920 [-/127.0.0.1/-/9ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443
2022-04-06 19:06:17,067 ERROR 920 [-/127.0.0.1/-/74ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest catch request error {"cause":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443},"isOperational":true,"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443}
2022-04-06 19:06:17,067 ERROR 920 [-/127.0.0.1/-/74ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"message":"getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443"}} {}
2022-04-06 19:06:17,071 ERROR 920 [-/127.0.0.1/-/78ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443
2022-04-06 19:06:17,194 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 10721339ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-06 19:39:06,832 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 889484ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-06 21:02:41,366 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 5014532ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-07 09:12:09,701 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 43224331ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-07 15:46:05,906 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 23636171ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-07 16:15:28,045 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 301871ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-07 17:21:08,208 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 3940142ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-07 17:41:50,347 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 301900ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-07 17:45:57,645 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 247283ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-07 18:02:22,747 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 64864ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-08 06:18:46,392 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 43263288ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-08 10:08:55,928 ERROR 920 [-/127.0.0.1/-/142ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest catch request error {"cause":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443},"isOperational":true,"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443}
2022-04-08 10:08:55,938 ERROR 920 [-/127.0.0.1/-/152ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"message":"getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443"}} {}
2022-04-08 10:08:55,939 ERROR 920 [-/127.0.0.1/-/153ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443
2022-04-08 14:13:35,356 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 28488534ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-08 14:15:00,737 ERROR 920 [-/127.0.0.1/-/30025ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest catch request error {"cause":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443},"isOperational":true,"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443}
2022-04-08 14:15:00,737 ERROR 920 [-/127.0.0.1/-/30025ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"message":"getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443"}} {}
2022-04-08 14:15:00,737 ERROR 920 [-/127.0.0.1/-/30025ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443
2022-04-09 02:38:49,610 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 43273903ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-10 08:27:18,507 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 107288800ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-10 08:29:44,482 ERROR 920 [-/127.0.0.1/-/11ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest catch request error {"cause":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443},"isOperational":true,"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443}
2022-04-10 08:29:44,482 ERROR 920 [-/127.0.0.1/-/12ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"message":"getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443"}} {}
2022-04-10 08:29:44,482 ERROR 920 [-/127.0.0.1/-/12ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443
2022-04-10 08:29:51,595 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 113043ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-10 20:31:03,497 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 43271887ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-11 09:15:02,705 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 45839127ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-11 13:27:21,986 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 15139210ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-11 14:06:34,430 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 2272390ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-11 14:47:10,997 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 2276532ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-11 19:00:00,783 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 14909686ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-04-12 10:53:00,440 ERROR 844 nodejs.ClusterClientNoResponseError: client no response in 57179579ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 844
hostname: talkdeMacBook-Pro.local

2022-05-11 09:39:40,904 ERROR 6404 [-//-/538ms POST /graphql] getTokenByRefreshToken-error
2022-05-11 09:39:41,933 ERROR 6404 [-//-/1741ms POST /graphql] getTokenByRefreshToken-error
2022-05-11 09:39:44,291 ERROR 6404 [-//-/459ms POST /graphql] getTokenByRefreshToken-error
2022-05-11 09:42:02,081 ERROR 6404 [-//-/842ms POST /graphql] getTokenByRefreshToken-error
2022-05-11 09:45:55,213 ERROR 6404 [-//-/7041ms POST /graphql] getTokenByRefreshToken-error
2022-05-11 09:45:57,356 ERROR 6404 [-//-/476ms POST /graphql] getTokenByRefreshToken-error
2022-05-11 10:00:44,457 ERROR 6400 nodejs.ClusterClientNoResponseError: client no response in 144546ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6400
hostname: talkdeMacBook-Pro.local

2022-05-11 10:02:37,729 ERROR 6400 nodejs.ClusterClientNoResponseError: client no response in 113263ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6400
hostname: talkdeMacBook-Pro.local

2022-05-11 10:37:44,946 ERROR 6400 nodejs.ClusterClientNoResponseError: client no response in 2027143ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6400
hostname: talkdeMacBook-Pro.local

2022-05-11 11:13:55,109 ERROR 6400 nodejs.ClusterClientNoResponseError: client no response in 2130126ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6400
hostname: talkdeMacBook-Pro.local

2022-05-11 12:21:03,694 ERROR 6400 nodejs.ClusterClientNoResponseError: client no response in 3944653ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6400
hostname: talkdeMacBook-Pro.local

2022-05-11 12:23:15,643 ERROR 6404 [-//-/1095ms POST /graphql] getTokenByRefreshToken-error
2022-05-11 12:23:29,507 ERROR 6404 [-//-/1844ms POST /graphql] getTokenByRefreshToken-error
2022-05-11 12:25:59,802 ERROR 6404 [-//-/2162ms POST /graphql] getTokenByRefreshToken-error
2022-05-11 12:28:33,156 ERROR 6404 [-//-/606ms POST /graphql] getTokenByRefreshToken-error
2022-05-11 12:34:46,518 ERROR 6404 [-//-/833ms POST /graphql] GeneralRequest error userSignin {"error":{"code":2024,"message":"This email is already registered."}} {"email":"18516360572@163.com","password":"talk199509L@","password_confirmation":"talk199509L@","utm_source":"","utm_medium":"","aff":"","id_type":"3","id_value":"e2dcfe2851fe2ac749d6fed2f206f21475c763a8","token":"7a5b714bf96de2e4c13d4639dfc403a7|jordan","session_id":"42bfe6699aa2aee3e2f83dcbfd3ee47b"}
2022-05-11 12:34:56,120 ERROR 6404 [-//-/741ms POST /graphql] GeneralRequest error userSignin {"error":{"code":2033,"message":"Invalid captcha","reason":"invalid_captcha"}} {"email":"18516360572@163.com","password":"talk199509L@","password_confirmation":"talk199509L@","utm_source":"","utm_medium":"","aff":"","id_type":"3","id_value":"e2dcfe2851fe2ac749d6fed2f206f21475c763a8","token":"7a5b714bf96de2e4c13d4639dfc403a7|jordan","session_id":"f5682a8309fadb18a4d46175c957f0f6"}
2022-05-11 12:35:35,721 ERROR 6404 [-//-/575ms POST /graphql] getTokenByRefreshToken-error
2022-05-11 12:35:42,458 ERROR 6404 [-//-/461ms POST /graphql] getTokenByRefreshToken-error
2022-05-11 12:35:54,552 ERROR 6404 [-//-/484ms POST /graphql] getTokenByRefreshToken-error
2022-05-11 12:36:53,057 ERROR 6404 [-//-/472ms POST /graphql] getTokenByRefreshToken-error
2022-05-11 13:27:05,265 ERROR 6404 [-/127.0.0.1/-/780044ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest catch request error {"cause":{"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"read"},"isOperational":true,"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"read"}
2022-05-11 13:27:05,265 ERROR 6404 [-/127.0.0.1/-/780044ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"message":"read ETIMEDOUT"}} {}
2022-05-11 13:27:05,266 ERROR 6404 [-/127.0.0.1/-/780045ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: read ETIMEDOUT
2022-05-11 17:12:49,340 ERROR 6400 nodejs.ClusterClientNoResponseError: client no response in 11944228ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6400
hostname: talkdeMacBook-Pro.local

2022-05-12 05:41:13,122 ERROR 6400 nodejs.ClusterClientNoResponseError: client no response in 43263324ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6400
hostname: talkdeMacBook-Pro.local

2022-05-12 08:00:06,248 ERROR 6404 [-/127.0.0.1/-/8320979ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest catch request error {"cause":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443},"isOperational":true,"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443}
2022-05-12 08:00:06,250 ERROR 6404 [-/127.0.0.1/-/8320981ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"message":"getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443"}} {}
2022-05-12 08:00:06,251 ERROR 6404 [-/127.0.0.1/-/8320982ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443
2022-05-12 09:48:33,983 ERROR 6400 nodejs.ClusterClientNoResponseError: client no response in 14839680ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6400
hostname: talkdeMacBook-Pro.local

2022-05-12 10:11:54,737 ERROR 6404 [-/127.0.0.1/-/30005ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest catch request error {"cause":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443},"isOperational":true,"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443}
2022-05-12 10:11:54,738 ERROR 6404 [-/127.0.0.1/-/30006ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"message":"getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443"}} {}
2022-05-12 10:11:54,738 ERROR 6404 [-/127.0.0.1/-/30006ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443
2022-05-12 16:28:06,957 ERROR 6400 nodejs.ClusterClientNoResponseError: client no response in 13582221ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6400
hostname: talkdeMacBook-Pro.local

2022-05-13 05:09:59,416 ERROR 6400 nodejs.ClusterClientNoResponseError: client no response in 43271674ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6400
hostname: talkdeMacBook-Pro.local

2022-05-13 09:17:55,252 ERROR 6400 nodejs.ClusterClientNoResponseError: client no response in 14875778ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6400
hostname: talkdeMacBook-Pro.local

2022-05-13 09:56:16,416 ERROR 6404 [-/127.0.0.1/-/2252814ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest catch request error {"cause":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443},"isOperational":true,"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443}
2022-05-13 09:56:16,417 ERROR 6404 [-/127.0.0.1/-/2252815ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"message":"getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443"}} {}
2022-05-13 09:56:16,417 ERROR 6404 [-/127.0.0.1/-/2252815ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443
2022-05-13 09:56:22,055 ERROR 6400 nodejs.ClusterClientNoResponseError: client no response in 2261714ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6400
hostname: talkdeMacBook-Pro.local

2022-05-13 10:48:44,846 ERROR 6400 nodejs.ClusterClientNoResponseError: client no response in 2342540ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6400
hostname: talkdeMacBook-Pro.local

2022-05-13 11:14:04,698 ERROR 6400 nodejs.ClusterClientNoResponseError: client no response in 624748ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6400
hostname: talkdeMacBook-Pro.local

2022-05-13 11:36:41,056 ERROR 6400 nodejs.ClusterClientNoResponseError: client no response in 136128ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6400
hostname: talkdeMacBook-Pro.local

2022-05-13 14:37:30,423 ERROR 6400 nodejs.ClusterClientNoResponseError: client no response in 6868525ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6400
hostname: talkdeMacBook-Pro.local

2022-05-13 16:04:36,826 ERROR 6404 [-/127.0.0.1/-/61413ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest catch request error {"cause":{"code":"ECONNRESET"},"isOperational":true,"code":"ECONNRESET"}
2022-05-13 16:04:36,826 ERROR 6404 [-/127.0.0.1/-/61413ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"message":"socket hang up"}} {}
2022-05-13 16:04:36,827 ERROR 6404 [-/127.0.0.1/-/61414ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: socket hang up
2022-05-31 08:39:46,647 ERROR 7138 [-//-/703ms POST /graphql] getTokenByRefreshToken-error
2022-05-31 08:43:55,142 ERROR 7138 [-//-/492ms POST /graphql] getTokenByRefreshToken-error
2022-05-31 08:50:27,030 ERROR 7138 [-//-/545ms POST /graphql] getTokenByRefreshToken-error
2022-05-31 08:52:54,667 ERROR 7138 [-//-/502ms POST /graphql] getTokenByRefreshToken-error
2022-05-31 10:43:20,275 ERROR 7137 nodejs.ClusterClientNoResponseError: client no response in 5617628ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7137
hostname: talkdeMacBook-Pro.local

2022-05-31 12:54:48,263 ERROR 7137 nodejs.ClusterClientNoResponseError: client no response in 4327592ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7137
hostname: talkdeMacBook-Pro.local

2022-05-31 13:25:14,724 ERROR 7137 nodejs.ClusterClientNoResponseError: client no response in 1626295ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7137
hostname: talkdeMacBook-Pro.local

2022-05-31 18:38:39,556 ERROR 7137 nodejs.ClusterClientNoResponseError: client no response in 17644698ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7137
hostname: talkdeMacBook-Pro.local

2022-05-31 19:19:48,255 ERROR 7137 nodejs.ClusterClientNoResponseError: client no response in 1606393ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7137
hostname: talkdeMacBook-Pro.local

2022-05-31 19:23:06,058 ERROR 7137 nodejs.ClusterClientNoResponseError: client no response in 197799ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7137
hostname: talkdeMacBook-Pro.local

2022-05-31 20:32:02,803 ERROR 7137 nodejs.ClusterClientNoResponseError: client no response in 2276491ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7137
hostname: talkdeMacBook-Pro.local

2022-05-31 20:32:03,569 ERROR 7138 [-/127.0.0.1/-/2258537ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"code":20051,"message":"","reason":"incorrect_signature_expired"}} {}
2022-05-31 20:32:03,570 ERROR 7138 [-/127.0.0.1/-/2258538ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: incorrect_signature_expired
2022-05-31 21:21:18,549 ERROR 7137 nodejs.ClusterClientNoResponseError: client no response in 2915610ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7137
hostname: talkdeMacBook-Pro.local

2022-06-01 06:57:18,012 ERROR 7137 nodejs.ClusterClientNoResponseError: client no response in 26831327ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7137
hostname: talkdeMacBook-Pro.local

2022-06-01 07:56:15,050 ERROR 7137 nodejs.ClusterClientNoResponseError: client no response in 1836833ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7137
hostname: talkdeMacBook-Pro.local

2022-06-01 08:43:53,308 ERROR 7137 nodejs.ClusterClientNoResponseError: client no response in 2738242ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7137
hostname: talkdeMacBook-Pro.local

2022-06-01 09:28:15,500 ERROR 7137 nodejs.ClusterClientNoResponseError: client no response in 1902093ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7137
hostname: talkdeMacBook-Pro.local

2022-06-01 09:59:31,570 ERROR 7137 nodejs.ClusterClientNoResponseError: client no response in 1851402ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7137
hostname: talkdeMacBook-Pro.local

2022-06-01 13:58:43,594 ERROR 7137 nodejs.ClusterClientNoResponseError: client no response in 14099413ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7137
hostname: talkdeMacBook-Pro.local

2022-06-01 13:58:55,847 ERROR 7138 [-/127.0.0.1/-/10708ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest catch request error {"cause":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443},"isOperational":true,"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443}
2022-06-01 13:58:55,848 ERROR 7138 [-/127.0.0.1/-/10709ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"message":"getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443"}} {}
2022-06-01 13:58:55,848 ERROR 7138 [-/127.0.0.1/-/10709ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443
2022-06-01 15:45:53,831 ERROR 7138 [-/127.0.0.1/-/256ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest catch request error {}
2022-06-01 15:45:53,832 ERROR 7138 [-/127.0.0.1/-/256ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"message":"apiRequest error 502 <html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n Unexpected token < in JSON at position 0"}} {}
2022-06-01 15:45:53,832 ERROR 7138 [-/127.0.0.1/-/257ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: apiRequest error 502 <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
 Unexpected token < in JSON at position 0
2022-06-01 20:13:33,545 ERROR 7138 [-/127.0.0.1/-/10659778ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest catch request error {"cause":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443},"isOperational":true,"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443}
2022-06-01 20:13:33,545 ERROR 7138 [-/127.0.0.1/-/10659778ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"message":"getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443"}} {}
2022-06-01 20:13:33,545 ERROR 7138 [-/127.0.0.1/-/10659778ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443
2022-06-01 20:13:48,372 ERROR 7137 nodejs.ClusterClientNoResponseError: client no response in 10674751ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7137
hostname: talkdeMacBook-Pro.local

2022-06-01 20:59:48,046 ERROR 7138 [-/127.0.0.1/-/105ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest catch request error {"cause":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443},"isOperational":true,"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"mapi.riostox.com","host":"mapi.riostox.com","port":443}
2022-06-01 20:59:48,050 ERROR 7138 [-/127.0.0.1/-/110ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"message":"getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443"}} {}
2022-06-01 20:59:48,052 ERROR 7138 [-/127.0.0.1/-/111ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: getaddrinfo ENOTFOUND mapi.riostox.com mapi.riostox.com:443
2022-06-01 21:34:04,367 ERROR 7137 nodejs.ClusterClientNoResponseError: client no response in 1991990ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7137
hostname: talkdeMacBook-Pro.local

2022-06-01 22:11:05,722 ERROR 7137 nodejs.ClusterClientNoResponseError: client no response in 2199588ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7137
hostname: talkdeMacBook-Pro.local

2022-06-01 22:15:12,053 ERROR 7137 nodejs.ClusterClientNoResponseError: client no response in 203668ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7137
hostname: talkdeMacBook-Pro.local

2022-06-02 06:48:13,600 ERROR 7137 nodejs.ClusterClientNoResponseError: client no response in 27301067ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7137
hostname: talkdeMacBook-Pro.local

2022-06-02 09:12:52,595 ERROR 7137 nodejs.ClusterClientNoResponseError: client no response in 4058010ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7137
hostname: talkdeMacBook-Pro.local

2022-06-02 09:34:32,067 ERROR 7137 nodejs.ClusterClientNoResponseError: client no response in 77538ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7137
hostname: talkdeMacBook-Pro.local

2022-06-02 10:01:13,653 ERROR 7137 nodejs.ClusterClientNoResponseError: client no response in 1113492ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/talk/Desktop/document/rio/exchange/portal/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7137
hostname: talkdeMacBook-Pro.local

2022-06-02 12:21:19,783 ERROR 7138 [-/127.0.0.1/-/250ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest catch request error {}
2022-06-02 12:21:19,785 ERROR 7138 [-/127.0.0.1/-/253ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] GeneralRequest error ticker {"error":{"message":"apiRequest error 502 <html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n Unexpected token < in JSON at position 0"}} {}
2022-06-02 12:21:19,785 ERROR 7138 [-/127.0.0.1/-/253ms SCHEDULE /__schedule?path=/Users/talk/Desktop/document/rio/exchange/portal/app/schedule/updateMarkets.js&interval=1m&type=worker] schedule market existed Error: apiRequest error 502 <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
 Unexpected token < in JSON at position 0
